#!/bin/bash

# 下面的幾個變量儘量採用默認值。如有必要，可根據實際情況更改。

# DNS 服務器的 IP 地址：
DNS_SERVERS="64.6.64.6 64.6.65.6 9.9.9.9"

# 虛擬機中的網關：
GATEWAY=10.0.2.2

# 宿主機中翻牆軟件（代理）的監聽端口：
GW_PROXY_PORT=8110


################################################################

# 完全開放防火牆：
./open-firewall

# 從嚴設置策略：
for chain in INPUT FORWARD OUTPUT; do
    iptables -t filter -P $chain DROP;
    ip6tables -t filter -P $chain DROP;
done

# 對 DNS 查詢放行：
for dns_server in $DNS_SERVERS; do
    iptables -A OUTPUT -p tcp -d $dns_server --dport 53 -j ACCEPT;
    iptables -A OUTPUT -p udp -d $dns_server --dport 53 -j ACCEPT;
done

# 放行發往宿主機內翻牆軟件的數據包：
iptables -A OUTPUT -p tcp -d $GATEWAY --dport $GW_PROXY_PORT -j ACCEPT

# 本機對本機完全開放：
iptables -t filter -A INPUT -s 127.0.0.1 -j ACCEPT
iptables -t filter -A OUTPUT -d 127.0.0.1 -j ACCEPT

# 以下規則完全基於連接狀態：

for stat in ESTABLISHED RELATED; do
    iptables -t filter -A INPUT -m state --state ${stat} -j ACCEPT;
    iptables -t filter -A OUTPUT -m state --state ${stat} -j ACCEPT;
    iptables -t filter -A INPUT -m conntrack --ctstate ${stat} -j ACCEPT;
    iptables -t filter -A OUTPUT -m conntrack --ctstate ${stat} -j ACCEPT;
done

for stat in EXPECTED SEEN_REPLY CONFIRMED; do
    iptables -t filter -A INPUT -m conntrack --ctstatus ${stat} -j ACCEPT;
    iptables -t filter -A OUTPUT -m conntrack --ctstatus ${stat} -j ACCEPT;
done
